services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME:-my-web-dev}
    restart: always
    ports:
      - '18080:8080'
    volumes:
      - ./dist:/usr/share/nginx/html
